// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analytics/stall-index": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Obtener Índice de Stall",
                "parameters": [
                    {
                        "type": "string",
                        "default": "ou",
                        "description": "Tier",
                        "name": "tier",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "gen9",
                        "description": "Generation",
                        "name": "gen",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api-pokemon-meta-go_internal_domain.StallIndexResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-pokemon-meta-go_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analytics/trend": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Obtener Tendencia de Uso",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pokemon Name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "ou",
                        "description": "Tier",
                        "name": "tier",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "gen9",
                        "description": "Generation",
                        "name": "gen",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api-pokemon-meta-go_internal_domain.PokemonTrendResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-pokemon-meta-go_internal_domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-pokemon-meta-go_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/anti-meta/speed-creepers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anti-Meta"
                ],
                "summary": "Obtener Anti-Meta Speed Creepers",
                "parameters": [
                    {
                        "type": "string",
                        "default": "ou",
                        "description": "Tier",
                        "name": "tier",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "gen9",
                        "description": "Generation",
                        "name": "gen",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api-pokemon-meta-go_internal_domain.SpeedCreeperItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-pokemon-meta-go_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/anti-meta/wallbreakers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anti-Meta"
                ],
                "summary": "Obtener Anti-Meta Wallbreakers",
                "parameters": [
                    {
                        "type": "string",
                        "default": "ou",
                        "description": "Tier",
                        "name": "tier",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "gen9",
                        "description": "Generation",
                        "name": "gen",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "ice",
                        "description": "Move Type",
                        "name": "move_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api-pokemon-meta-go_internal_domain.WallbreakerItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-pokemon-meta-go_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meta/snapshot": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meta"
                ],
                "summary": "Obtener Snapshot del Meta",
                "parameters": [
                    {
                        "type": "string",
                        "default": "ou",
                        "description": "Tier",
                        "name": "tier",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "gen9",
                        "description": "Generation",
                        "name": "gen",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api-pokemon-meta-go_internal_domain.MetaSnapshotItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-pokemon-meta-go_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api-pokemon-meta-go_internal_domain.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api-pokemon-meta-go_internal_domain.MetaSnapshotItem": {
            "type": "object",
            "properties": {
                "abilities": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "base_stats": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "items": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "moves": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string"
                },
                "natures": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "rank": {
                    "type": "integer"
                },
                "spreads": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tera_types": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "top_ability": {
                    "type": "string"
                },
                "top_item": {
                    "type": "string"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "usage_percentage": {
                    "type": "number"
                }
            }
        },
        "api-pokemon-meta-go_internal_domain.PokemonTrendResponse": {
            "type": "object",
            "properties": {
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api-pokemon-meta-go_internal_domain.TrendPoint"
                    }
                },
                "pokemon_name": {
                    "type": "string"
                }
            }
        },
        "api-pokemon-meta-go_internal_domain.SpeedCreeperItem": {
            "type": "object",
            "properties": {
                "ataque": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "usage_percentage": {
                    "type": "number"
                },
                "velocidad": {
                    "type": "integer"
                }
            }
        },
        "api-pokemon-meta-go_internal_domain.StallIndexResponse": {
            "type": "object",
            "properties": {
                "stall_percentage": {
                    "type": "number"
                }
            }
        },
        "api-pokemon-meta-go_internal_domain.TrendPoint": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "api-pokemon-meta-go_internal_domain.WallbreakerItem": {
            "type": "object",
            "properties": {
                "atk_base": {
                    "type": "integer"
                },
                "move_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "usage_percentage": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Pokémon Meta API",
	Description:      "API de analítica competitiva de Pokémon migrada a Go.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
